# 设置undertow为开发模式，支持热部署 myeclipse自动部署
undertow.devMode=false
#undertow 的端口号，默认 8080，配置 * 为随机端口
undertow.port=9101
#默认为localhost
undertow.host=0.0.0.0
undertow.resourcePath =src/main/webapp, classpath\:static
# session 过期时间，注意单位是秒
undertow.session.timeout=600
# 支持 session 热加载，避免依赖于 session 的登录型项目反复登录，默认值为 true。仅用于 devMode，生产环境无影响
undertow.session.hotSwap=false

#启动模式dev product-不会输出请求日志
jboot.app.mode=product

#main数据源
jboot.datasource.name = appmain
jboot.datasource.appmain.type = mysql
jboot.datasource.appmain.url = jdbc:mysql://127.0.0.1:3306/onex2_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
#jboot.datasource.appmain.url = jdbc:mysql://127.0.0.1:3306/javasaas-game-backup?useUnicode=true&characterEncoding=utf-8&useSSL=false
#jboot.datasource.appmain.url = jdbc:mysql://192.168.1.201:3306/1x2_pro?useUnicode=true&characterEncoding=utf-8&useSSL=false
jboot.datasource.appmain.user = root
jboot.datasource.appmain.password = 123456
#jboot.datasource.appmain.url = jdbc:mysql://54.151.220.75:3306/onex2_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
#jboot.datasource.appmain.user = onex2_db
#jboot.datasource.appmain.password = NthAiX2mRmNFWwr3
jboot.datasource.appmain.devMode = true
jboot.datasource.appmain.initialSize=5
jboot.datasource.appmain.minIdle=5
jboot.datasource.appmain.maxActive=100
jboot.datasource.appmain.maxWait=10000
jboot.datasource.appmain.timeBetweenEvictionRunsMillis=60000
jboot.datasource.appmain.minEvictableIdleTimeMillis=300000

#连接池管理
jboot.datasource.factory=druid

#配置JWT的http头的key，默认为 Jwt
jboot.web.jwt.httpHeaderName=authorization
#配置JWT的密钥
jboot.web.jwt.secret=c601b339e0497b4afa585c167210757b
#配置JWT的过期时间，默认7天604800
jboot.web.jwt.validityPeriod=604800000

#关闭ID缓存
jboot.model.idCacheEnable=false

#是否启用大写转换，比如 user_age 自动转为为 UserAge，只对 Model 生效，默认值为 true
jboot.json.camelCaseJsonStyleEnable = false
#是否转换任何地方，比如 map.put("my_field") 默认输出为 myField，默认值为 false
jboot.json.camelCaseToLowerCaseAnyway = false
#是否跳过 null 值输出，map.put("key",null)，则 key 值不输，默认值为 true
jboot.json.skipNullValueField = true
#配置输出的时间格式，默认值为 yyyy-MM-dd HH:mm:ss
jboot.json.timestampPattern = yyyy-MM-dd HH:mm:ss
# 是否跳过 model 的 attr，只用 bean 的 getter 来渲染
jboot.json.skipModelAttrs = false
# 是否值跳过 bean 的 getter，只用 model 的 attr 渲染
jboot.json.skipBeanGetters = true

#redis
jboot.redis.host=127.0.0.1
jboot.redis.port=6379
jboot.redis.database=7
jboot.redis.password=

#应用配置
web.app.debug=true
web.app.defaultTeantId=10000
web.app.loginDebug=false
web.app.debuguid=1
web.app.debugmid=2853
web.app.sphinxAddHistoryCmd=D:/DevTools/sphinx/sphinx-3.1.1/bin/indexer -c D:/DevTools/sphinx/sphinx-3.1.1/etc/order_history.conf  order_history_add --rotate

#结算配置
#计算佣金扣除方式，1从字典读取，0采用下注时计算1X2不扣除，HDP和OU按下注时扣除
web.settlement.commisionFeeType=0
web.settlement.negativeBalanceMax=50000

#联赛配置
web.league.apiUrl=https://v3.football.api-sports.io
web.league.xRapidapiKey=35f1dd86200122041f8f74c850fbc05b

#阿里云OSS配置（请根据实际情况修改）
oss.aliyun.endpoint=http://oss-ap-southeast-1.aliyuncs.com
oss.aliyun.accessKeyId=LTAI5tCj9rxJfZsb5mjd3UPh
oss.aliyun.accessKeySecret=Zd0sqWI84XWAXJalf3d6SJJ4nWiKJP
oss.aliyun.bucketName=onex2
oss.aliyun.urlPrefix=http://onex2.oss-ap-southeast-1.aliyuncs.com
oss.aliyun.tempDir=temp/images
